-- SQL SEED SCRIPT FOR STUDENT EXAM PORTAL
-- Run this in the Supabase SQL Editor to populate your database with sample data.

-- 1. Insert Sample Exams
INSERT INTO public.exams (exam_name, course_code, department, semester, exam_date, exam_time, venue, fee, registration_deadline, description, is_active)
VALUES 
('End Semester Theory - Mathematics I', 'MATH101', 'Computer Science', 1, '2026-05-15', '09:30 AM', 'Examination Hall A', 500, '2026-05-01', 'Final theory examination for Engineering Mathematics I.', true),
('Computer Programming in C', 'CS102', 'Computer Science', 2, '2026-05-18', '02:00 PM', 'Lab Complex 1', 450, '2026-05-05', 'Practical and Theory combined evaluation.', true),
('Digital Logic Design', 'ECE201', 'Electronics', 3, '2026-05-20', '09:30 AM', 'Block B - Room 204', 500, '2026-05-07', 'Covers combinational and sequential circuit design.', true),
('Operating Systems', 'CS301', 'Computer Science', 5, '2026-05-22', '09:30 AM', 'Main Auditorium', 600, '2026-05-10', 'Process management, Memory, and File systems.', true),
('Database Management Systems', 'CS302', 'Information Technology', 4, '2026-05-25', '02:00 PM', 'IT Block - Ground Floor', 550, '2026-05-12', 'SQL, Normalization, and Transactions.', true);

-- 2. Note: To seed registrations, you need User IDs. 
-- Since User IDs are generated by Supabase Auth, you should register a student account first,
-- then use the following template to add sample registrations for testing charts.

/*
INSERT INTO public.registrations (student_id, exam_id, status, payment_status, payment_amount, registered_at)
SELECT 
  'YOUR_USER_ID_HERE', 
  id, 
  CASE WHEN random() > 0.5 THEN 'confirmed' ELSE 'pending' END, 
  CASE WHEN random() > 0.3 THEN 'paid' ELSE 'unpaid' END,
  fee,
  CURRENT_TIMESTAMP - (random() * interval '7 days')
FROM public.exams;
*/

-- 3. Sample Notifications for the Admin Dashboard to look active
-- (Only useful if you have a user ID)
